-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               5.5.16 - MySQL Community Server (GPL)
-- Server OS:                    Win32
-- HeidiSQL version:             7.0.0.4053
-- Date/time:                    2013-05-29 00:57:20
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET FOREIGN_KEY_CHECKS=0 */;

-- Dumping structure for table weorder.setting
DROP TABLE IF EXISTS `setting`;
CREATE TABLE IF NOT EXISTS `setting` (
  `setting_id` int(11) NOT NULL AUTO_INCREMENT,
  `store_id` int(11) NOT NULL DEFAULT '0',
  `group` varchar(32) NOT NULL,
  `key` varchar(64) NOT NULL,
  `value` text NOT NULL,
  `serialized` tinyint(1) NOT NULL,
  PRIMARY KEY (`setting_id`)
) ENGINE=MyISAM AUTO_INCREMENT=1308 DEFAULT CHARSET=utf8;

-- Dumping data for table weorder.setting: 145 rows
DELETE FROM `setting`;
/*!40000 ALTER TABLE `setting` DISABLE KEYS */;
INSERT INTO `setting` (`setting_id`, `store_id`, `group`, `key`, `value`, `serialized`) VALUES
	(1, 0, 'shipping', 'shipping_sort_order', '3', 0),
	(2, 0, 'sub_total', 'sub_total_sort_order', '1', 0),
	(3, 0, 'sub_total', 'sub_total_status', '1', 0),
	(4, 0, 'tax', 'tax_status', '1', 0),
	(5, 0, 'total', 'total_sort_order', '9', 0),
	(6, 0, 'total', 'total_status', '1', 0),
	(7, 0, 'tax', 'tax_sort_order', '5', 0),
	(8, 0, 'free_checkout', 'free_checkout_sort_order', '1', 0),
	(9, 0, 'cod', 'cod_sort_order', '5', 0),
	(10, 0, 'cod', 'cod_total', '0.01', 0),
	(11, 0, 'cod', 'cod_order_status_id', '1', 0),
	(12, 0, 'cod', 'cod_geo_zone_id', '0', 0),
	(13, 0, 'cod', 'cod_status', '1', 0),
	(14, 0, 'shipping', 'shipping_status', '1', 0),
	(15, 0, 'shipping', 'shipping_estimator', '1', 0),
	(27, 0, 'coupon', 'coupon_sort_order', '4', 0),
	(28, 0, 'coupon', 'coupon_status', '1', 0),
	(34, 0, 'flat', 'flat_sort_order', '1', 0),
	(35, 0, 'flat', 'flat_status', '1', 0),
	(36, 0, 'flat', 'flat_geo_zone_id', '0', 0),
	(37, 0, 'flat', 'flat_tax_class_id', '9', 0),
	(341, 0, 'featured', 'product', '', 0),
	(342, 0, 'featured', 'featured_product', '43,40,42,49,46,47,28', 0),
	(41, 0, 'flat', 'flat_cost', '5.00', 0),
	(42, 0, 'credit', 'credit_sort_order', '7', 0),
	(43, 0, 'credit', 'credit_status', '1', 0),
	(53, 0, 'reward', 'reward_sort_order', '2', 0),
	(54, 0, 'reward', 'reward_status', '1', 0),
	(56, 0, 'affiliate', 'affiliate_module', 'a:1:{i:0;a:4:{s:9:"layout_id";s:2:"10";s:8:"position";s:12:"column_right";s:6:"status";s:1:"1";s:10:"sort_order";s:1:"1";}}', 1),
	(767, 0, 'category', 'category_module', 'a:2:{i:0;a:4:{s:9:"layout_id";s:1:"3";s:8:"position";s:11:"column_left";s:6:"status";s:1:"1";s:10:"sort_order";s:1:"1";}i:1;a:4:{s:9:"layout_id";s:1:"2";s:8:"position";s:11:"column_left";s:6:"status";s:1:"0";s:10:"sort_order";s:1:"1";}}', 1),
	(60, 0, 'account', 'account_module', 'a:1:{i:0;a:4:{s:9:"layout_id";s:1:"6";s:8:"position";s:12:"column_right";s:6:"status";s:1:"1";s:10:"sort_order";s:1:"1";}}', 1),
	(1306, 0, 'viewed', 'show_on_product', '1', 0),
	(1307, 0, 'viewed', 'viewed_module', 'a:1:{i:0;a:6:{s:11:"image_width";s:3:"175";s:12:"image_height";s:3:"252";s:9:"layout_id";s:1:"2";s:8:"position";s:14:"content_bottom";s:6:"status";s:1:"1";s:10:"sort_order";s:1:"1";}}', 1),
	(1299, 0, 'config', 'config_error_log', '1', 0),
	(1297, 0, 'config', 'config_compression', '0', 0),
	(1298, 0, 'config', 'config_error_display', '1', 0),
	(1296, 0, 'config', 'config_encryption', '7f339d82bc9ee711ed084c4a101fbb25', 0),
	(1295, 0, 'config', 'config_password', '1', 0),
	(1294, 0, 'config', 'config_maintenance', '0', 0),
	(94, 0, 'voucher', 'voucher_sort_order', '8', 0),
	(95, 0, 'voucher', 'voucher_status', '1', 0),
	(103, 0, 'free_checkout', 'free_checkout_status', '1', 0),
	(104, 0, 'free_checkout', 'free_checkout_order_status_id', '1', 0),
	(109, 0, 'banner', 'banner_module', 'a:1:{i:0;a:8:{s:9:"banner_id";s:1:"6";s:5:"width";s:3:"182";s:6:"height";s:3:"182";s:11:"resize_type";s:7:"default";s:9:"layout_id";s:1:"3";s:8:"position";s:11:"column_left";s:6:"status";s:1:"1";s:10:"sort_order";s:1:"3";}}', 1),
	(1291, 0, 'config', 'config_seo_url', '0', 0),
	(1292, 0, 'config', 'config_file_extension_allowed', 'txt\r\npng\r\njpe\r\njpeg\r\njpg\r\ngif\r\nbmp\r\nico\r\ntiff\r\ntif\r\nsvg\r\nsvgz\r\nzip\r\nrar\r\nmsi\r\ncab\r\nmp3\r\nqt\r\nmov\r\npdf\r\npsd\r\nai\r\neps\r\nps\r\ndoc\r\nrtf\r\nxls\r\nppt\r\nodt\r\nods', 0),
	(1288, 0, 'config', 'config_secure', '0', 0),
	(1289, 0, 'config', 'config_shared', '0', 0),
	(1290, 0, 'config', 'config_robots', 'abot\r\ndbot\r\nebot\r\nhbot\r\nkbot\r\nlbot\r\nmbot\r\nnbot\r\nobot\r\npbot\r\nrbot\r\nsbot\r\ntbot\r\nvbot\r\nybot\r\nzbot\r\nbot.\r\nbot/\r\n_bot\r\n.bot\r\n/bot\r\n-bot\r\n:bot\r\n(bot\r\ncrawl\r\nslurp\r\nspider\r\nseek\r\naccoona\r\nacoon\r\nadressendeutschland\r\nah-ha.com\r\nahoy\r\naltavista\r\nananzi\r\nanthill\r\nappie\r\narachnophilia\r\narale\r\naraneo\r\naranha\r\narchitext\r\naretha\r\narks\r\nasterias\r\natlocal\r\natn\r\natomz\r\naugurfind\r\nbackrub\r\nbannana_bot\r\nbaypup\r\nbdfetch\r\nbig brother\r\nbiglotron\r\nbjaaland\r\nblackwidow\r\nblaiz\r\nblog\r\nblo.\r\nbloodhound\r\nboitho\r\nbooch\r\nbradley\r\nbutterfly\r\ncalif\r\ncassandra\r\nccubee\r\ncfetch\r\ncharlotte\r\nchurl\r\ncienciaficcion\r\ncmc\r\ncollective\r\ncomagent\r\ncombine\r\ncomputingsite\r\ncsci\r\ncurl\r\ncusco\r\ndaumoa\r\ndeepindex\r\ndelorie\r\ndepspid\r\ndeweb\r\ndie blinde kuh\r\ndigger\r\nditto\r\ndmoz\r\ndocomo\r\ndownload express\r\ndtaagent\r\ndwcp\r\nebiness\r\nebingbong\r\ne-collector\r\nejupiter\r\nemacs-w3 search engine\r\nesther\r\nevliya celebi\r\nezresult\r\nfalcon\r\nfelix ide\r\nferret\r\nfetchrover\r\nfido\r\nfindlinks\r\nfireball\r\nfish search\r\nfouineur\r\nfunnelweb\r\ngazz\r\ngcreep\r\ngenieknows\r\ngetterroboplus\r\ngeturl\r\nglx\r\ngoforit\r\ngolem\r\ngrabber\r\ngrapnel\r\ngralon\r\ngriffon\r\ngromit\r\ngrub\r\ngulliver\r\nhamahakki\r\nharvest\r\nhavindex\r\nhelix\r\nheritrix\r\nhku www octopus\r\nhomerweb\r\nhtdig\r\nhtml index\r\nhtml_analyzer\r\nhtmlgobble\r\nhubater\r\nhyper-decontextualizer\r\nia_archiver\r\nibm_planetwide\r\nichiro\r\niconsurf\r\niltrovatore\r\nimage.kapsi.net\r\nimagelock\r\nincywincy\r\nindexer\r\ninfobee\r\ninformant\r\ningrid\r\ninktomisearch.com\r\ninspector web\r\nintelliagent\r\ninternet shinchakubin\r\nip3000\r\niron33\r\nisraeli-search\r\nivia\r\njack\r\njakarta\r\njavabee\r\njetbot\r\njumpstation\r\nkatipo\r\nkdd-explorer\r\nkilroy\r\nknowledge\r\nkototoi\r\nkretrieve\r\nlabelgrabber\r\nlachesis\r\nlarbin\r\nlegs\r\nlibwww\r\nlinkalarm\r\nlink validator\r\nlinkscan\r\nlockon\r\nlwp\r\nlycos\r\nmagpie\r\nmantraagent\r\nmapoftheinternet\r\nmarvin/\r\nmattie\r\nmediafox\r\nmediapartners\r\nmercator\r\nmerzscope\r\nmicrosoft url control\r\nminirank\r\nmiva\r\nmj12\r\nmnogosearch\r\nmoget\r\nmonster\r\nmoose\r\nmotor\r\nmultitext\r\nmuncher\r\nmuscatferret\r\nmwd.search\r\nmyweb\r\nnajdi\r\nnameprotect\r\nnationaldirectory\r\nnazilla\r\nncsa beta\r\nnec-meshexplorer\r\nnederland.zoek\r\nnetcarta webmap engine\r\nnetmechanic\r\nnetresearchserver\r\nnetscoop\r\nnewscan-online\r\nnhse\r\nnokia6682/\r\nnomad\r\nnoyona\r\nnutch\r\nnzexplorer\r\nobjectssearch\r\noccam\r\nomni\r\nopen text\r\nopenfind\r\nopenintelligencedata\r\norb search\r\nosis-project\r\npack rat\r\npageboy\r\npagebull\r\npage_verifier\r\npanscient\r\nparasite\r\npartnersite\r\npatric\r\npear.\r\npegasus\r\nperegrinator\r\npgp key agent\r\nphantom\r\nphpdig\r\npicosearch\r\npiltdownman\r\npimptrain\r\npinpoint\r\npioneer\r\npiranha\r\nplumtreewebaccessor\r\npogodak\r\npoirot\r\npompos\r\npoppelsdorf\r\npoppi\r\npopular iconoclast\r\npsycheclone\r\npublisher\r\npython\r\nrambler\r\nraven search\r\nroach\r\nroad runner\r\nroadhouse\r\nrobbie\r\nrobofox\r\nrobozilla\r\nrules\r\nsalty\r\nsbider\r\nscooter\r\nscoutjet\r\nscrubby\r\nsearch.\r\nsearchprocess\r\nsemanticdiscovery\r\nsenrigan\r\nsg-scout\r\nshai\'hulud\r\nshark\r\nshopwiki\r\nsidewinder\r\nsift\r\nsilk\r\nsimmany\r\nsite searcher\r\nsite valet\r\nsitetech-rover\r\nskymob.com\r\nsleek\r\nsmartwit\r\nsna-\r\nsnappy\r\nsnooper\r\nsohu\r\nspeedfind\r\nsphere\r\nsphider\r\nspinner\r\nspyder\r\nsteeler/\r\nsuke\r\nsuntek\r\nsupersnooper\r\nsurfnomore\r\nsven\r\nsygol\r\nszukacz\r\ntach black widow\r\ntarantula\r\ntempleton\r\n/teoma\r\nt-h-u-n-d-e-r-s-t-o-n-e\r\ntheophrastus\r\ntitan\r\ntitin\r\ntkwww\r\ntoutatis\r\nt-rex\r\ntutorgig\r\ntwiceler\r\ntwisted\r\nucsd\r\nudmsearch\r\nurl check\r\nupdated\r\nvagabondo\r\nvalkyrie\r\nverticrawl\r\nvictoria\r\nvision-search\r\nvolcano\r\nvoyager/\r\nvoyager-hc\r\nw3c_validator\r\nw3m2\r\nw3mir\r\nwalker\r\nwallpaper\r\nwanderer\r\nwauuu\r\nwavefire\r\nweb core\r\nweb hopper\r\nweb wombat\r\nwebbandit\r\nwebcatcher\r\nwebcopy\r\nwebfoot\r\nweblayers\r\nweblinker\r\nweblog monitor\r\nwebmirror\r\nwebmonkey\r\nwebquest\r\nwebreaper\r\nwebsitepulse\r\nwebsnarf\r\nwebstolperer\r\nwebvac\r\nwebwalk\r\nwebwatch\r\nwebwombat\r\nwebzinger\r\nwhizbang\r\nwhowhere\r\nwild ferret\r\nworldlight\r\nwwwc\r\nwwwster\r\nxenu\r\nxget\r\nxift\r\nxirq\r\nyandex\r\nyanga\r\nyeti\r\nyodao\r\nzao\r\nzippp\r\nzyborg', 0),
	(1293, 0, 'config', 'config_file_mime_allowed', 'text/plain\r\nimage/png\r\nimage/jpeg\r\nimage/jpeg\r\nimage/jpeg\r\nimage/gif\r\nimage/bmp\r\nimage/vnd.microsoft.icon\r\nimage/tiff\r\nimage/tiff\r\nimage/svg+xml\r\nimage/svg+xml\r\napplication/zip\r\napplication/x-rar-compressed\r\napplication/x-msdownload\r\napplication/vnd.ms-cab-compressed\r\naudio/mpeg\r\nvideo/quicktime\r\nvideo/quicktime\r\napplication/pdf\r\nimage/vnd.adobe.photoshop\r\napplication/postscript\r\napplication/postscript\r\napplication/postscript\r\napplication/msword\r\napplication/rtf\r\napplication/vnd.ms-excel\r\napplication/vnd.ms-powerpoint\r\napplication/vnd.oasis.opendocument.text\r\napplication/vnd.oasis.opendocument.spreadsheet', 0),
	(1287, 0, 'config', 'config_fraud_status_id', '7', 0),
	(1286, 0, 'config', 'config_fraud_score', '', 0),
	(1285, 0, 'config', 'config_fraud_key', '', 0),
	(1284, 0, 'config', 'config_fraud_detection', '0', 0),
	(1283, 0, 'config', 'config_alert_emails', '', 0),
	(1282, 0, 'config', 'config_account_mail', '0', 0),
	(1281, 0, 'config', 'config_alert_mail', '0', 0),
	(1280, 0, 'config', 'config_smtp_timeout', '5', 0),
	(1279, 0, 'config', 'config_smtp_port', '25', 0),
	(1278, 0, 'config', 'config_smtp_password', '', 0),
	(1277, 0, 'config', 'config_smtp_username', '', 0),
	(1276, 0, 'config', 'config_smtp_host', '', 0),
	(1275, 0, 'config', 'config_mail_parameter', '', 0),
	(1274, 0, 'config', 'config_mail_protocol', 'mail', 0),
	(1273, 0, 'config', 'config_ftp_status', '0', 0),
	(1272, 0, 'config', 'config_ftp_root', '', 0),
	(1271, 0, 'config', 'config_ftp_password', '', 0),
	(1270, 0, 'config', 'config_ftp_username', '', 0),
	(1267, 0, 'config', 'config_image_cart_height', '47', 0),
	(1268, 0, 'config', 'config_ftp_host', 'localhost', 0),
	(1269, 0, 'config', 'config_ftp_port', '21', 0),
	(1266, 0, 'config', 'config_image_cart_width', '47', 0),
	(1264, 0, 'config', 'config_image_wishlist_width', '47', 0),
	(1265, 0, 'config', 'config_image_wishlist_height', '47', 0),
	(1263, 0, 'config', 'config_image_compare_height', '90', 0),
	(1262, 0, 'config', 'config_image_compare_width', '90', 0),
	(1261, 0, 'config', 'config_image_related_height', '252', 0),
	(1260, 0, 'config', 'config_image_related_width', '185', 0),
	(1259, 0, 'config', 'config_image_additional_height', '54', 0),
	(1258, 0, 'config', 'config_image_additional_width', '37', 0),
	(1257, 0, 'config', 'config_image_product_height', '600', 0),
	(1256, 0, 'config', 'config_image_product_width', '400', 0),
	(1255, 0, 'config', 'config_image_popup_height', '400', 0),
	(1254, 0, 'config', 'config_image_popup_width', '227', 0),
	(1253, 0, 'config', 'config_image_thumb_height', '400', 0),
	(1252, 0, 'config', 'config_image_thumb_width', '227', 0),
	(1251, 0, 'config', 'config_image_news_height', '341', 0),
	(1250, 0, 'config', 'config_image_news_width', '242', 0),
	(1249, 0, 'config', 'config_image_category_height', '80', 0),
	(1248, 0, 'config', 'config_image_category_width', '80', 0),
	(1247, 0, 'config', 'config_icon', 'data/cart.png', 0),
	(1246, 0, 'config', 'config_logo', 'data/wesale.jpg', 0),
	(1245, 0, 'config', 'config_return_status_id', '2', 0),
	(1244, 0, 'config', 'config_return_id', '0', 0),
	(1243, 0, 'config', 'config_commission', '5', 0),
	(1241, 0, 'config', 'config_stock_status_id', '5', 0),
	(1242, 0, 'config', 'config_affiliate_id', '4', 0),
	(1240, 0, 'config', 'config_stock_checkout', '0', 0),
	(1239, 0, 'config', 'config_stock_warning', '0', 0),
	(1238, 0, 'config', 'config_stock_display', '0', 0),
	(1237, 0, 'config', 'config_complete_status_id', '5', 0),
	(1236, 0, 'config', 'config_order_status_id', '1', 0),
	(1234, 0, 'config', 'config_order_edit', '100', 0),
	(1235, 0, 'config', 'config_invoice_prefix', 'INV-2013-00', 0),
	(764, 0, 'slideshow', 'slideshow_module', 'a:2:{i:0;a:7:{s:9:"banner_id";s:1:"8";s:5:"width";s:3:"759";s:6:"height";s:3:"380";s:9:"layout_id";s:2:"12";s:8:"position";s:11:"content_top";s:6:"status";s:1:"1";s:10:"sort_order";s:1:"1";}i:1;a:7:{s:9:"banner_id";s:1:"7";s:5:"width";s:3:"996";s:6:"height";s:3:"481";s:9:"layout_id";s:1:"1";s:8:"position";s:11:"content_top";s:6:"status";s:1:"1";s:10:"sort_order";s:1:"1";}}', 1),
	(1233, 0, 'config', 'config_checkout_id', '5', 0),
	(1232, 0, 'config', 'config_guest_checkout', '1', 0),
	(1231, 0, 'config', 'config_cart_weight', '1', 0),
	(1230, 0, 'config', 'config_account_id', '3', 0),
	(1229, 0, 'config', 'config_customer_price', '0', 0),
	(1228, 0, 'config', 'config_customer_group_display', 'a:1:{i:0;s:1:"1";}', 1),
	(1227, 0, 'config', 'config_customer_group_id', '1', 0),
	(1226, 0, 'config', 'config_customer_online', '0', 0),
	(1225, 0, 'config', 'config_tax_customer', 'shipping', 0),
	(1224, 0, 'config', 'config_tax_default', 'shipping', 0),
	(1223, 0, 'config', 'config_vat', '0', 0),
	(1222, 0, 'config', 'config_tax', '1', 0),
	(1221, 0, 'config', 'config_voucher_max', '1000', 0),
	(1220, 0, 'config', 'config_voucher_min', '1', 0),
	(1219, 0, 'config', 'config_download', '1', 0),
	(1218, 0, 'config', 'config_review_status', '1', 0),
	(1217, 0, 'config', 'config_product_count', '1', 0),
	(1214, 0, 'config', 'config_weight_class_id', '1', 0),
	(1215, 0, 'config', 'config_catalog_limit', '15', 0),
	(1216, 0, 'config', 'config_admin_limit', '20', 0),
	(1213, 0, 'config', 'config_length_class_id', '1', 0),
	(1212, 0, 'config', 'config_currency_auto', '1', 0),
	(1211, 0, 'config', 'config_currency', 'USD', 0),
	(1210, 0, 'config', 'config_admin_language', 'vi', 0),
	(1209, 0, 'config', 'config_language', 'vi', 0),
	(1208, 0, 'config', 'config_zone_id', '3776', 0),
	(1207, 0, 'config', 'config_country_id', '230', 0),
	(1206, 0, 'config', 'config_layout_id', '4', 0),
	(1205, 0, 'config', 'config_template', 'default', 0),
	(1204, 0, 'config', 'config_meta_description', 'Weorder', 0),
	(1203, 0, 'config', 'config_title', 'Đặt hàng quốc tế - Weorder', 0),
	(1202, 0, 'config', 'config_fax', '', 0),
	(1200, 0, 'config', 'config_email', 'admin@admin.com', 0),
	(1201, 0, 'config', 'config_telephone', '123456789', 0),
	(1199, 0, 'config', 'config_address', 'Address 1', 0),
	(1198, 0, 'config', 'config_owner', 'Đặt hàng quốc tế', 0),
	(1197, 0, 'config', 'config_name', 'Đặt hàng quốc tế', 0),
	(1300, 0, 'config', 'config_error_filename', 'error.txt', 0),
	(1301, 0, 'config', 'config_google_analytics', '', 0),
	(1305, 0, 'viewed', 'viewed_count', '4', 0);
/*!40000 ALTER TABLE `setting` ENABLE KEYS */;
/*!40014 SET FOREIGN_KEY_CHECKS=1 */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
